### ISSUE TITLE
RequestTime Error

### ISSUE THREAD

**Issue by bl8dd3r** [aw/picolisp-awscurl#3]
When trying to list bucket contents I get a *RequestTimeTooSkewed* error.
On the same machine I'm using the aws-cli tool with no errors, so I don't think it's a local clock issue (and it is correct).
Here's the (reformated) error
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>RequestTimeTooSkewed</Code>
  <Message>The difference between the request time and the current time is too large.</Message>
  <RequestTime>20180618T141243Z</RequestTime>
  <ServerTime>2018-06-18T13:12:33Z</ServerTime>
  <MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds>
  <RequestId>DC0FFAB0A37D39BA</RequestId>
  <HostId>cq/tUHOChltiEzThRH7DPr5dFVFYiAjv2rvFY3u9mAAgC54mKjWQfhJfffnYI0lqMhR+XBIl6bo=</HostId>
</Error>
```
As you can see the request time is an hour ahead of the server time, I'm currently in BST which is 1 hour ahead of GMT (but only until October).  Could this be a Timezone/UTC issue?

I get the same type of error when trying the bucket example given in the internal example. So here is the verbose output from
`./awscurl.l --verbose --service s3 --host awscurl.s3.amazonaws.com --endpoint /mybucket --query 'a=Prefix&b=Marker'`
[out.txt](https://github.com/aw/picolisp-awscurl/files/2111459/out.txt)

(This is going to be an awesome tool, I can't wait for the Python purge!)

**Comment by aw** [comment]
Thanks @bl8dd3r

My computer is set to UTC, so I didn't noticed this error. Nice catch!

I just pushed a commit which ensures the timestamp is in UTC, rather than local time.

**Comment by bl8dd3r** [comment]
That got it. Fixed.
